/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDefinitelyMetadata,
  IDefinitelyMetadataInterface,
} from "../IDefinitelyMetadata";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDefinitelyMetadata__factory {
  static readonly abi = _abi;
  static createInterface(): IDefinitelyMetadataInterface {
    return new utils.Interface(_abi) as IDefinitelyMetadataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDefinitelyMetadata {
    return new Contract(address, _abi, signerOrProvider) as IDefinitelyMetadata;
  }
}
