"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockRevoke__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "definitelyMemberships_",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "account",
                type: "address",
            },
        ],
        name: "addToDenyList",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "definitelyMemberships",
        outputs: [
            {
                internalType: "contract IDefinitelyMemberships",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "account",
                type: "address",
            },
        ],
        name: "removeFromDenyList",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "id",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "addToDenyList_",
                type: "bool",
            },
        ],
        name: "revoke",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
const _bytecode = "0x608060405234801561001057600080fd5b506040516102bf3803806102bf83398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b61022c806100936000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063215048cd1461005157806340a73c13146100665780637d491b3114610079578063b903364c146100a8575b600080fd5b61006461005f3660046101ba565b6100bb565b005b6100646100743660046101ea565b61011e565b60005461008c906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b6100646100b63660046101ba565b610188565b60005460405163f817242d60e01b81526001600160a01b0383811660048301529091169063f817242d906024015b600060405180830381600087803b15801561010357600080fd5b505af1158015610117573d6000803e3d6000fd5b5050505050565b600054604051632a8c348f60e21b81526004810184905282151560248201526001600160a01b039091169063aa30d23c90604401600060405180830381600087803b15801561016c57600080fd5b505af1158015610180573d6000803e3d6000fd5b505050505050565b60005460405163752d547760e01b81526001600160a01b0383811660048301529091169063752d5477906024016100e9565b6000602082840312156101cc57600080fd5b81356001600160a01b03811681146101e357600080fd5b9392505050565b600080604083850312156101fd57600080fd5b823591506020830135801515811461021457600080fd5b80915050925092905056fea164736f6c634300080f000a";
const isSuperArgs = (xs) => xs.length > 1;
class MockRevoke__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(definitelyMemberships_, overrides) {
        return super.deploy(definitelyMemberships_, overrides || {});
    }
    getDeployTransaction(definitelyMemberships_, overrides) {
        return super.getDeployTransaction(definitelyMemberships_, overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.MockRevoke__factory = MockRevoke__factory;
MockRevoke__factory.bytecode = _bytecode;
MockRevoke__factory.abi = _abi;
