"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockTransfer__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "definitelyMemberships_",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [],
        name: "definitelyMemberships",
        outputs: [
            {
                internalType: "contract IDefinitelyMemberships",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "id",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "to",
                type: "address",
            },
        ],
        name: "transfer",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
const _bytecode = "0x608060405234801561001057600080fd5b506040516101c53803806101c583398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b610132806100936000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80637d491b311461003b578063b7760c8f1461006a575b600080fd5b60005461004e906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b61007d6100783660046100e9565b61007f565b005b60005460405163d454dfaf60e01b8152600481018490526001600160a01b0383811660248301529091169063d454dfaf90604401600060405180830381600087803b1580156100cd57600080fd5b505af11580156100e1573d6000803e3d6000fd5b505050505050565b600080604083850312156100fc57600080fd5b8235915060208301356001600160a01b038116811461011a57600080fd5b80915050925092905056fea164736f6c634300080f000a";
const isSuperArgs = (xs) => xs.length > 1;
class MockTransfer__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(definitelyMemberships_, overrides) {
        return super.deploy(definitelyMemberships_, overrides || {});
    }
    getDeployTransaction(definitelyMemberships_, overrides) {
        return super.getDeployTransaction(definitelyMemberships_, overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.MockTransfer__factory = MockTransfer__factory;
MockTransfer__factory.bytecode = _bytecode;
MockTransfer__factory.abi = _abi;
