/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface DefinitelyInvitesInterface extends utils.Interface {
  functions: {
    "claimInvite()": FunctionFragment;
    "definitelyMemberships()": FunctionFragment;
    "inviteAvailable(address)": FunctionFragment;
    "inviteCooldown()": FunctionFragment;
    "memberLastSentInvite(address)": FunctionFragment;
    "sendClaimableInvite(address)": FunctionFragment;
    "sendImediateInvite(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claimInvite"
      | "definitelyMemberships"
      | "inviteAvailable"
      | "inviteCooldown"
      | "memberLastSentInvite"
      | "sendClaimableInvite"
      | "sendImediateInvite"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimInvite",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "definitelyMemberships",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inviteAvailable",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "inviteCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "memberLastSentInvite",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sendClaimableInvite",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sendImediateInvite",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimInvite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "definitelyMemberships",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inviteAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inviteCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberLastSentInvite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendClaimableInvite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendImediateInvite",
    data: BytesLike
  ): Result;

  events: {
    "InviteClaimed(address)": EventFragment;
    "MemberInvited(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "InviteClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MemberInvited"): EventFragment;
}

export interface InviteClaimedEventObject {
  invited: string;
}
export type InviteClaimedEvent = TypedEvent<[string], InviteClaimedEventObject>;

export type InviteClaimedEventFilter = TypedEventFilter<InviteClaimedEvent>;

export interface MemberInvitedEventObject {
  invited: string;
  invitedBy: string;
}
export type MemberInvitedEvent = TypedEvent<
  [string, string],
  MemberInvitedEventObject
>;

export type MemberInvitedEventFilter = TypedEventFilter<MemberInvitedEvent>;

export interface DefinitelyInvites extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DefinitelyInvitesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimInvite(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    definitelyMemberships(overrides?: CallOverrides): Promise<[string]>;

    inviteAvailable(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    inviteCooldown(overrides?: CallOverrides): Promise<[BigNumber]>;

    memberLastSentInvite(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sendClaimableInvite(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendImediateInvite(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  claimInvite(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  definitelyMemberships(overrides?: CallOverrides): Promise<string>;

  inviteAvailable(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  inviteCooldown(overrides?: CallOverrides): Promise<BigNumber>;

  memberLastSentInvite(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sendClaimableInvite(
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendImediateInvite(
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimInvite(overrides?: CallOverrides): Promise<void>;

    definitelyMemberships(overrides?: CallOverrides): Promise<string>;

    inviteAvailable(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    inviteCooldown(overrides?: CallOverrides): Promise<BigNumber>;

    memberLastSentInvite(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sendClaimableInvite(
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sendImediateInvite(
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "InviteClaimed(address)"(
      invited?: PromiseOrValue<string> | null
    ): InviteClaimedEventFilter;
    InviteClaimed(
      invited?: PromiseOrValue<string> | null
    ): InviteClaimedEventFilter;

    "MemberInvited(address,address)"(
      invited?: PromiseOrValue<string> | null,
      invitedBy?: PromiseOrValue<string> | null
    ): MemberInvitedEventFilter;
    MemberInvited(
      invited?: PromiseOrValue<string> | null,
      invitedBy?: PromiseOrValue<string> | null
    ): MemberInvitedEventFilter;
  };

  estimateGas: {
    claimInvite(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    definitelyMemberships(overrides?: CallOverrides): Promise<BigNumber>;

    inviteAvailable(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inviteCooldown(overrides?: CallOverrides): Promise<BigNumber>;

    memberLastSentInvite(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sendClaimableInvite(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendImediateInvite(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimInvite(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    definitelyMemberships(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inviteAvailable(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inviteCooldown(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    memberLastSentInvite(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sendClaimableInvite(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendImediateInvite(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
